apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pvj009tqd-go 
  janus-idp.io/tekton: pvj009tqd-go
  backstage.io/kubernetes-id: pvj009tqd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pvj009tqd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  