apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pvj009tqd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pvj009tqd-go 
  name: pvj009tqd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pvj009tqd-go 
